"""Type stubs for the OpenBLUP native extension module (``openblup._internal``)."""

from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import numpy.typing as npt

__version__: str

SparseCSCTuple = Tuple[
    npt.NDArray[np.float64],
    npt.NDArray[np.int64],
    npt.NDArray[np.int64],
    Tuple[int, int],
]
"""(data, indices, indptr, shape) for a scipy-compatible CSC sparse matrix."""

class Pedigree:
    """A pedigree representing parent-offspring relationships."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_csv(path: str) -> "Pedigree":
        """Load from CSV with columns animal, sire, dam ("0"/""/"NA" = unknown)."""
        ...
    @staticmethod
    def from_triples(
        triples: Sequence[Tuple[str, Optional[str], Optional[str]]],
    ) -> "Pedigree": ...
    def add_animal(
        self, animal: str, sire: Optional[str] = None, dam: Optional[str] = None
    ) -> None: ...
    def n_animals(self) -> int: ...
    def __len__(self) -> int: ...
    def sort(self) -> None:
        """Topologically sort (parents before offspring); required before A-inverse."""
        ...
    def validate(self) -> None: ...
    def is_sorted(self) -> bool: ...
    def compute_a_inverse(self) -> SparseCSCTuple:
        """Henderson's rules ignoring inbreeding (pedigree must be sorted)."""
        ...
    def compute_a_inverse_with_inbreeding(self) -> SparseCSCTuple:
        """Henderson's rules with Meuwissen & Luo inbreeding (pedigree must be sorted)."""
        ...
    def compute_inbreeding(self) -> npt.NDArray[np.float64]: ...
    def animal_ids(self) -> List[str]:
        """Animal IDs in pedigree order (the A-inverse row/column order once sorted)."""
        ...

class MixedModel:
    """Accumulates data, fixed and random effects, then fits via REML."""

    def __init__(self) -> None: ...
    def set_data(
        self,
        columns: Dict[str, Union[Sequence[float], Sequence[int], Sequence[str], npt.NDArray[Any]]],
    ) -> None: ...
    def load_csv(self, path: str) -> None: ...
    def as_factor(self, column: str) -> None: ...
    def drop_missing(self, column: str) -> int:
        """Drop rows where a numeric column is NaN; returns the number dropped."""
        ...
    def n_rows(self) -> int: ...
    def columns(self) -> List[str]: ...
    def set_response(self, column: str) -> None: ...
    def add_fixed(self, formula: str) -> None:
        """E.g. "mu + rep": intercept plus treatment contrasts for factor rep."""
        ...
    def add_random(
        self,
        column: str,
        ginverse: Optional[SparseCSCTuple] = None,
        levels: Optional[Sequence[str]] = None,
    ) -> None: ...
    def add_random_pedigree(self, column: str, pedigree: Pedigree) -> None:
        """Animal-model term: levels = pedigree animals, G-inverse = A-inverse."""
        ...
    def set_max_iterations(self, n: int) -> None: ...
    def set_convergence_tol(self, tol: float) -> None: ...
    def set_algorithm(self, algorithm: str) -> None:
        """"ai" (Average Information, default) or "em"."""
        ...
    def set_drop_missing_response(self, drop: bool) -> None: ...
    def fit(self) -> "FitResult": ...

class FitResult:
    """The result of fitting a mixed model via REML."""

    converged: bool
    n_iterations: int
    n_obs: int
    n_fixed_params: int
    n_variance_params: int

    def summary(self) -> str: ...
    def variance_components(self) -> Dict[str, float]: ...
    def variance_components_se(self) -> Dict[str, float]: ...
    def at_boundary(self) -> Dict[str, bool]:
        """Variance parameters that converged to the boundary (effectively zero)."""
        ...
    def fixed_effects(self) -> List[Tuple[str, str, float, float]]:
        """(term, level, estimate, se) per fixed-effect column."""
        ...
    def fixed_effects_cov(self) -> npt.NDArray[np.float64]: ...
    def random_effects(self) -> Dict[str, npt.NDArray[np.float64]]: ...
    def random_effects_se(self) -> Dict[str, npt.NDArray[np.float64]]: ...
    def reliabilities(self) -> Dict[str, npt.NDArray[np.float64]]: ...
    def random_effect_levels(self) -> Dict[str, List[str]]: ...
    def residuals(self) -> npt.NDArray[np.float64]: ...
    def wald_tests(self) -> List[Dict[str, Any]]: ...
    def log_likelihood(self) -> float: ...
    def aic(self) -> float: ...
    def bic(self) -> float: ...
    def iteration_history(self) -> List[Dict[str, Any]]: ...

def compute_a_inverse(ped: Pedigree, inbreeding: bool = True) -> SparseCSCTuple:
    """Sort the pedigree if needed and return its A-inverse as a CSC tuple."""
    ...

def compute_inbreeding(ped: Pedigree) -> npt.NDArray[np.float64]: ...
def compute_g_matrix(
    markers: npt.NDArray[np.float64],
    allele_freqs: Optional[npt.NDArray[np.float64]] = None,
) -> npt.NDArray[np.float64]:
    """VanRaden (2008) method 1 genomic relationship matrix from 0/1/2 markers."""
    ...
