pub mod ar1;
pub mod diagonal;
pub mod factor_analytic;
mod identity;
pub mod known;
pub mod kronecker;
mod relationship;
pub mod spec;
mod traits;
pub mod unstructured;

pub use ar1::AR1;
pub use diagonal::Diagonal;
pub use factor_analytic::{fa1, fa2, FactorAnalytic};
pub use identity::Identity;
pub use known::Known;
pub use kronecker::{kronecker_product, KroneckerStruct};
pub use relationship::Relationship;
pub use spec::StructureSpec;
pub use traits::VarStruct;
pub use unstructured::Unstructured;
